### ISSUE TITLE
Falling block dupe fix

### ISSUE THREAD

**Issue by angrynerd** [fxmorin/carpet-fixes#8] opened 2021-05-24 00:01 UTC
The falling block dupe fix seems to be active even when its set to false. I set it to false in the config and manually on the server and the sand generator that was previously working for one of my members no longer does. I apologize for reporting so many issues, but they are happening so i figure its better to mention them.

**Comment by angrynerd** [comment] 2021-05-24 00:14
Noted it seems to work when none of the fixes in this mod are applied. I am currrently unable to test which one specifically is breaking it. I will updated this when i am able to.

**Comment by angrynerd** [comment] 2021-05-24 06:52
Ok so after testing this issue is caused by the blockCollisionCheckFix being set to true. This breaks endportal falling entity dupers.

**Comment by fxmorin** [comment] 2021-05-24 09:44
LOL, so fixing the collision system causes falling blocks to not dupe. Wow that's funny, ill make a condition for it

**Comment by fxmorin** [comment] 2021-05-24 13:46
Fixed in v0.0.4

**Comment by angrynerd** [comment] 2021-05-25 01:23
Ok I just tested this fix and now it seems its actually worse now the sand duping machine doesnt function even when all of the rules are turned off.

**Comment by fxmorin** [comment] 2021-05-25 02:01
Have you tested this same duper without carpet-fixes?

**Comment by fxmorin** [comment] 2021-05-25 02:12
Ok fix for this will be out in tomorrow's release also. I'll keep the issue open this time tho

**Comment by angrynerd** [comment] 2021-05-26 03:48
Can confirm that this is fixed for blockCollisionCheckFix, however the incorrectBounceLogicFix rule now breaks slime block based sand duping. The sand goes into the end portal rather than staying in the over world and then duping into the end. fully replicating the behavior of the actual falling entity fix rather than the collision fix which still left the blocks in the overworld but didnt dupe the entities. for reference this is the specific machine in use for testing https://youtu.be/Qiq_cHQVM_I. This may be considered as intended behavior as im assuming the sand entities are bouncing off the slime instead of being stuck to them.

**Comment by fxmorin** [comment] 2021-05-29 05:05
Yup this is intended behavior.

**Comment by fxmorin** [comment] 2021-05-29 05:05
AAAAAAHHHH That was a shulkercraft video, my eye's

**Closed by fxmorin** 2021-05-29 05:05 UTC
