### ISSUE TITLE
Incompatible with latest Carpet release

### ISSUE THREAD

**Issue by Boobies** [fxmorin/carpet-fixes#15] opened 2021-08-17 11:56 UTC
Disabled all other mods.

```
[11:53:50] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoSuchFieldError: categories
	at carpetfixes.helpers.RulePresets.setVanilla(RulePresets.java:79) ~[carpetfixes-1.17-0.0.10.jar:?]
	at carpetfixes.helpers.RulePresets.runChangePresetRule(RulePresets.java:12) ~[carpetfixes-1.17-0.0.10.jar:?]
	at carpetfixes.CarpetFixesServer.onServerLoaded(CarpetFixesServer.java:29) ~[carpetfixes-1.17-0.0.10.jar:?]
	at carpet.CarpetServer.lambda$onServerLoaded$0(CarpetServer.java:91) ~[fabric-carpet-1.17.1-1.4.45+v210811.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at carpet.CarpetServer.onServerLoaded(CarpetServer.java:88) ~[fabric-carpet-1.17.1-1.4.45+v210811.jar:?]
	at net.minecraft.server.MinecraftServer.handler$zbc000$serverLoaded(MinecraftServer.java:2291) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_1132.method_3823(class_1132.java:71) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[11:53:51] [Server thread/ERROR]: This crash report has been saved to: /home/ubuntu/.local/share/multimc/instances/1.17.1/.minecraft/crash-reports/crash-2021-08-17_11.53.51-server.txt
[11:53:51] [Server thread/INFO]: Stopping server
[11:53:51] [Server thread/INFO]: Saving players
[11:53:51] [Server thread/INFO]: Saving worlds
[11:53:51] [Server thread/ERROR]: Exception stopping the server
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_3218.method_8621()" because "â˜ƒ" is null
	at net.minecraft.server.MinecraftServer.method_3723(MinecraftServer.java:588) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_3782(MinecraftServer.java:624) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_1132.method_3782(class_1132.java:212) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:734) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Process was killed by user.
```

**Comment by FxMorin** [comment] 2021-08-17 23:07
`Process was killed by user.` 👀
I don't wanna die, so I shall look into it

**Comment by FxMorin** [comment] 2021-08-18 01:13
Can you try: [Test Version](https://github.com/fxmorin/carpet-fixes/suites/3526183253/artifacts/84268531)
It should have fixed the issue!

**Comment by LeFauxMatt** [comment] 2021-08-19 04:56
The Test Version does not fix the issue for me. Here are my latest.log and crash report for reference - 
https://hastebin.com/aqepitaxap.sql
https://hastebin.com/payayuvaye.yaml

**Comment by FxMorin** [comment] 2021-08-21 22:16
This makes no sense tho, since last carpet commit was: [link](https://github.com/gnembon/fabric-carpet/commit/7fb5e47da5045c2f0c295a930aa8d5401531b486#diff-17faa056d474348d7aa41fb2bc849fb82524d48d520c15efe02966f46f893221)
So `categories` def does exist. I'll do a bit of digging

**Comment by FxMorin** [comment] 2021-08-24 17:05
Attempt to use this version: [fix](https://github.com/fxmorin/carpet-fixes/suites/3583192724/artifacts/86203426)
This should fix the issue until I have time to look into what caused the problem to begin with

**Comment by Hendrix-Shen** [comment] 2021-08-25 09:40
The problem seems to be caused by the carpet mod modifying some data types.
For detail:
https://github.com/gnembon/fabric-carpet/commit/7fb5e47da5045c2f0c295a930aa8d5401531b486#diff-17faa056d474348d7aa41fb2bc849fb82524d48d520c15efe02966f46f893221
<pre>
    public final ImmutableList<String> extraInfo;   ->    public final List<String> extraInfo; 
    public final ImmutableList<String> categories;  ->    public final List<String> categories; 
    public final ImmutableList<String> options;     ->    public final List<String> options; 
</pre>

**Comment by FxMorin** [comment] 2021-08-29 22:12
I thought that also but it shouldn't have made them invisible to the extension. I feel like it might need to be fixed wither getters on fabric-carpet's side

**Closed as completed** 2021-08-30 16:11 UTC
